### PR TITLE
feat: Format help logs with emojis and embeds

### PR DESCRIPTION
**Pull request by DenverCoder1**
This PR stylizes the `#help_logs` channel with emojis and embeds.

This makes the logs easier to read and distinguish different types of log messages from each other.

This PR also includes the close method and thread mention in the close thread logs.

Old logs:

image

New logs:

image

image

This has been tested locally.

### CODE REVIEW

**Review by Soheab — APPROVED** [review]

**Review by MaskDuck — APPROVED** [review]
noice

**Comment by TAG-Epic** [comment]
Merge conflicts, else everything LGTM

**Comment by koala9712** [comment]
Might as well give the embeds a colour?

**Comment by DenverCoder1** [comment]
:heavy_check_mark: Added colors

:heavy_check_mark: Made titles link to the threads

:heavy_check_mark: Added text version of user names & ids to avoid possible issues with Discord caching (eg. #invalid-user)

**Comment by DenverCoder1** [comment]
Also added the topic to the embed sent to the user on thread close

**Review by koala9712 — COMMENTED** [review]
Looks good

**Pull request merged**
